### ISSUE TITLE
java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by a-v-ebrahimi** [Bhat015/optimize_battery#2]
When I call OptimizeBattery.stopOptimizingBatteryUsage(), I receive this error, I've added android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS to manifest :
```

E/DartMessenger(12723): Uncaught exception in binary message listener
E/DartMessenger(12723): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(12723): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:431)
E/DartMessenger(12723): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:282)
E/DartMessenger(12723): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/DartMessenger(12723): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/DartMessenger(12723): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$AIEPqY6mWzaNK15HekX9bftoAXs.run(Unknown Source:12)
E/DartMessenger(12723): 	at android.os.Handler.handleCallback(Handler.java:938)
E/DartMessenger(12723): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/DartMessenger(12723): 	at android.os.Looper.loopOnce(Looper.java:226)
E/DartMessenger(12723): 	at android.os.Looper.loop(Looper.java:313)
E/DartMessenger(12723): 	at android.app.ActivityThread.main(ActivityThread.java:8582)
E/DartMessenger(12723): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(12723): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
E/DartMessenger(12723): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

```

**Comment by Bhat015** [comment]
Can you please share how `OptimizeBattery.stopOptimizingBatteryUsage()` was called? That would be helpful.
Thanks

**Comment by a-v-ebrahimi** [comment]
@Bhat015 
Please check my code:

> showCustomDialog(
        context,
        Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            HtmlWidget(
              L(context).batteryIsOptimizedMayStopAudio,
              textStyle: getTextStyle(),
            ),
          ],
        ),
        dialogTitle: L(context).openBatteryOptimizationSettings,
        firstActionTitle: L(context).goto,
        onFirstPress: (cont) {
          //OptimizeBattery.openBatteryOptimizationSettings();
          OptimizeBattery.stopOptimizingBatteryUsage();
        },
        hideOnFirstPress: true,
        secondActionTitle: L(context).cancelReturn,
        onSecondPress: (cont) {
          Navigator.pop(cont);
        });

**Comment by Bhat015** [comment]
Sure

**Comment by Bhat015** [comment]
@a-v-ebrahimi Issue is fixed.
Thanks to @panalgin . Will push this out soon

**Comment by a-v-ebrahimi** [comment]
Thanks, it does now crash now, 
but OptimizeBattery.stopOptimizingBatteryUsage() does nothing at all, does not display a dialog or anything else.

**Comment by Bhat015** [comment]
You need to add the below permission in android mainfest file to use `stopOptimizingBatteryUsage()`

`<uses-permission  android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>`

Also, please check if the battery is already optimized before calling `stopOptimizingBatteryUsage()`

**Comment by Bhat015** [comment]
I would recommend you to use it like this
```
  if (Platform.isAndroid) {
      final isIgnoringBatteryOptimization =
          await OptimizeBattery.isIgnoringBatteryOptimizations();
      if (!isIgnoringBatteryOptimization)
        await OptimizeBattery.stopOptimizingBatteryUsage();
    }
```
